In [1]:
import pandas as pd
import numpy as np

In [2]:
info={
    "Name":["Prashant","Amit","Sumit"],
    "Class":["AIML 6B",12,11],
    "CGPA":[8.8,8.7,7.9]
}

In [3]:
df=pd.DataFrame(info)

df

       Name    Class  CGPA
0  Prashant  AIML 6B   8.8
1      Amit       12   8.7
2     Sumit       11   7.9

**SERIES data structure**

SERIES: 1d labelled array

In [4]:
arr=np.array([3,4,1,2,6])

In [5]:
s=pd.Series(arr)

In [6]:
s

0    3
1    4
2    1
3    2
4    6
dtype: int64

In [7]:
type(s)

pandas.core.series.Series

In [8]:
print(s[0],s[1],sep="\n")

3
4

In [11]:
age=np.array([22,24,21,20])
name=np.array(["rahul","prem","amit","sumit"]) #labels

data=pd.Series(age,index=name)

In [12]:
data

rahul    22
prem     24
amit     21
sumit    20
dtype: int64

In [15]:
print(data["amit"]) # acess by label
print(data[2]) # acess by index

21
21

C:\Users\prash\AppData\Local\Temp\ipykernel_106588\2194752506.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(data[2]) # acess by index

In [16]:
print(data.index)

Index(['rahul', 'prem', 'amit', 'sumit'], dtype='object')

In [17]:
print(df.columns)

Index(['Name', 'Class', 'CGPA'], dtype='object')

**DATAFRAME DATA STRUCTURE**

In [26]:
data={
    "Name":["prashant","amit","sumit"],
    "Class":[11,12,10]
}

In [27]:
df=pd.DataFrame(data)
df

       Name  Class
0  prashant     11
1      amit     12
2     sumit     10

In [30]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Class'], dtype='object')

In [33]:
# craeting dataframe using list of list

df=pd.DataFrame([["Prashnat",23,8.8],["amit",22,7.7],["sumit",20,9.5]])
df

          0   1    2
0  Prashnat  23  8.8
1      amit  22  7.7
2     sumit  20  9.5

In [35]:
df=pd.DataFrame([["Prashnat",23,8.8],["amit",22,7.7],["sumit",20,9.5]],columns=["Name","Age","CGPA"])
df

       Name  Age  CGPA
0  Prashnat   23   8.8
1      amit   22   7.7
2     sumit   20   9.5

In [36]:
df=pd.DataFrame([["Prashnat",23,8.8],["amit",22,7.7],["sumit",20,9.5]],index=["A","B","C"])
df

          0   1    2
A  Prashnat  23  8.8
B      amit  22  7.7
C     sumit  20  9.5

In [37]:
df=pd.DataFrame([["Prashnat",23,8.8],["amit",22,7.7],["sumit",20,9.5]],columns=["Name","Age","CGPA"],index=["A","B","C"])
df

       Name  Age  CGPA
A  Prashnat   23   8.8
B      amit   22   7.7
C     sumit   20   9.5